import type { ProjectEntry } from "./experience-data";

export const PROJECTS_WITH_CASE_STUDIES: ProjectEntry[] = [
  {
    id: "eth-ed",
    title: "Eth.Ed",
    summary: "AI-powered Web3 learning platform with gamified lessons, ENS-based certificates, and smart contract micropayments.",
    stack: "Next.js, TypeScript, Solidity, AI Agents, ENS",
    role: "Solo — Full-Stack Engineer",
    year: "2026",
    impact: "Won ENS Pool Prize at ETHMumbai 2026. Built end-to-end from architecture to deployment.",
    href: "/projects/eth-ed",
    tags: ["Solo", "Next.js", "AI", "Solidity", "ENS"],
    caseStudy: {
      status: "Shipped · Won ENS Pool Prize at ETHMumbai 2026",
      overview: "Eth.Ed is an AI-powered Web3 education platform designed to simplify Ethereum learning through structured courses, interactive lessons, wallet-based authentication, and verifiable blockchain credentials. The platform combines modern educational experiences with decentralized technologies to make learning engaging, transparent, and rewarding.",
      problem: "Web3 education is fragmented across blogs, documentation, YouTube videos, and community forums, making it difficult for newcomers to follow a structured learning path. Existing platforms also lack verifiable credentials that users can truly own.",
      whyBuilt: "Eth.Ed was built to create a structured learning ecosystem where users could progress through curated educational content while earning blockchain-based credentials that remain permanently associated with their digital identity.",
      objectives: [
        "Provide structured, progression-based Web3 curriculum",
        "Enable wallet-based authentication for true ownership",
        "Issue verifiable ENS-linked credentials on completion",
        "Integrate AI to personalize learning paths",
        "Build scalable architecture from day one",
      ],
      myRole: "Architected and developed the platform from scratch. Built frontend and backend workflows, implemented wallet connectivity and authentication, integrated AI-assisted educational features, designed scalable APIs, and developed ENS-based certification workflows.",
      architecture: "Next.js App Router handles all routing with React Server Components for data fetching. Smart contracts deployed on Ethereum handle credential issuance. ENS integration links certificates to user identity. AI layer provides personalized content recommendations. Backend APIs serve course content and track progress.",
      techStack: [
        { category: "Frontend", items: ["Next.js", "React", "TypeScript", "TailwindCSS"] },
        { category: "Blockchain", items: ["Solidity", "Ethereum", "ENS", "Wallet Auth"] },
        { category: "AI & Backend", items: ["AI Agents", "REST APIs", "Web3.js"] },
      ],
      challenges: [
        { title: "Wallet Auth UX", detail: "Making wallet-based authentication as smooth as email login required extensive UX iteration to avoid alienating non-crypto users." },
        { title: "On-chain Credential Gas Costs", detail: "Balancing the cost of issuing credentials on-chain with user experience required careful contract optimization and batching strategies." },
        { title: "AI Content Personalization", detail: "Integrating AI recommendations without introducing latency into the core learning flow required careful async architecture decisions." },
      ],
      process: [
        "Defined product requirements and user journeys at ETHMumbai hackathon",
        "Architected smart contract structure for credential issuance",
        "Built core learning flow and progression system",
        "Integrated wallet authentication and ENS resolution",
        "Added AI-powered content recommendations",
        "Deployed contracts and submitted for ENS Pool Prize judging",
      ],
      features: [
        { title: "Structured Curriculum", detail: "Curated learning paths guiding users from Ethereum basics to advanced protocol concepts." },
        { title: "Wallet Authentication", detail: "Sign-in with Ethereum — no passwords, users own their account via their wallet." },
        { title: "ENS Credentials", detail: "Certificates issued on-chain and linked to ENS names, permanently verifiable." },
        { title: "AI Personalization", detail: "AI layer adapts content recommendations based on user progress and learning pace." },
      ],
      implementation: "The platform was fully architected and shipped within the ETHMumbai hackathon window. Contracts were deployed on testnet with mainnet migration planned post-hackathon. The ENS credential system uses resolver records to attach achievement metadata to user ENS names.",
      futureImprovements: [
        "Expand curriculum to cover DeFi, DAOs, and Layer 2 ecosystems",
        "Mainnet credential deployment with gasless signing via relayers",
        "Community-contributed course modules",
        "Mobile app for on-the-go learning",
      ],
      lessonsLearned: [
        "Hackathon timelines force extremely focused product decisions — every feature needs clear justification",
        "Wallet UX is still the biggest barrier for Web3 adoption",
        "ENS is underutilized as an identity and credentials layer",
      ],
    },
  },
  {
    id: "local-ai",
    title: "Local AI Infrastructure",
    summary: "Distributed AI workflow platform using Python, Ollama, Docker, Playwright and Open WebUI for autonomous orchestration and local LLM execution across multiple systems.",
    stack: "Python, Docker, Ollama, Playwright, Open WebUI",
    role: "Solo — Systems Engineer",
    year: "2026",
    impact: "Fully self-hosted AI infrastructure for autonomous workflow orchestration and browser automation.",
    href: "/projects/local-ai",
    tags: ["Solo", "Python", "Docker", "Ollama", "AI"],
    caseStudy: {
      status: "Active · Personal Infrastructure",
      overview: "A distributed local AI ecosystem built using Ollama, Docker, Playwright, and Open WebUI to enable privacy-first AI workflows capable of browser automation, intelligent reasoning, and engineering task automation without relying on cloud-hosted language models.",
      problem: "Cloud AI systems introduce latency, recurring API costs, privacy concerns, and limited customization. Workflows depending on external APIs are fragile — rate limits, outages, and pricing changes directly impact productivity.",
      whyBuilt: "To build a modular AI platform capable of orchestrating multiple local language models and intelligent automation workflows while maintaining complete ownership of data and infrastructure.",
      objectives: [
        "Run LLMs entirely on local hardware with no cloud dependency",
        "Enable browser automation driven by AI reasoning",
        "Build reusable workflow orchestration primitives",
        "Manage infrastructure remotely via SSH and Tailscale",
        "Keep all data private and infrastructure owned end-to-end",
      ],
      myRole: "Designed the overall architecture, configured all Dockerized services, integrated Ollama-hosted models, built browser automation pipelines using Playwright, developed workflow orchestration logic, and managed remote infrastructure access.",
      architecture: "Docker Compose manages all services as isolated containers. Ollama serves local LLMs via API. Open WebUI provides a browser-based interface. Playwright handles browser automation triggered by AI outputs. Tailscale provides secure remote access across devices. Python orchestration layer ties everything together.",
      techStack: [
        { category: "AI & Models", items: ["Ollama", "Open WebUI", "Local LLMs"] },
        { category: "Infrastructure", items: ["Docker", "Docker Compose", "SSH", "Tailscale"] },
        { category: "Automation", items: ["Python", "Playwright", "Workflow Orchestration"] },
      ],
      challenges: [
        { title: "Hardware Resource Management", detail: "Running multiple LLMs simultaneously requires careful memory allocation and model swapping strategies to avoid OOM errors." },
        { title: "Cross-device Networking", detail: "Establishing secure, low-latency connections across multiple machines required a robust overlay network solution — Tailscale solved this cleanly." },
        { title: "AI Output Reliability", detail: "LLM outputs are non-deterministic. Building reliable automation on top of them required output validation, retry logic, and structured prompting." },
      ],
      process: [
        "Researched local LLM options and selected Ollama for its API compatibility",
        "Set up Docker Compose infrastructure with service isolation",
        "Configured Open WebUI for model interaction",
        "Built initial Playwright automation scripts",
        "Integrated AI reasoning layer to drive browser automation",
        "Set up Tailscale for secure remote access",
        "Developed reusable workflow templates",
      ],
      features: [
        { title: "Local LLM Execution", detail: "Multiple models (Llama, Mistral, etc.) running via Ollama with API-compatible endpoints." },
        { title: "Browser Automation", detail: "Playwright-driven workflows that navigate, extract, and interact with web applications." },
        { title: "Workflow Orchestration", detail: "Python-based orchestration layer chaining AI reasoning with automated actions." },
        { title: "Remote Access", detail: "Tailscale overlay network enables secure management from any device." },
      ],
      implementation: "All services run inside Docker containers orchestrated via Compose. The Python automation layer communicates with Ollama's local API to generate decisions, then passes those decisions to Playwright for execution. Structured output formats ensure predictable automation behavior.",
      futureImprovements: [
        "Add a web dashboard for workflow monitoring and scheduling",
        "Expand to multi-node distributed inference",
        "Build a visual workflow builder",
        "Integrate vector database for long-term AI memory",
      ],
      lessonsLearned: [
        "Local infrastructure gives a level of control and privacy that cloud solutions simply can't match",
        "Structured prompting is as important as model selection for reliable automation",
        "Docker Compose is underrated for personal infrastructure projects",
      ],
    },
  },
  {
    id: "ai-workflow",
    title: "AI Workflow Automation",
    summary: "Automation framework integrating local AI models with browser automation and custom workflows to handle repetitive engineering tasks and document processing.",
    stack: "Python, Playwright, LLMs, AI Agents",
    role: "Solo — Automation Engineer",
    year: "2026",
    impact: "Replaced hours of manual engineering work with intelligent automated pipelines.",
    href: "/projects/ai-workflow",
    tags: ["Solo", "Python", "AI", "Automation", "Playwright"],
    caseStudy: {
      status: "Active · Personal Tooling",
      overview: "An automation framework that combines local language models with browser automation to execute repetitive engineering workflows, automate research, documentation, and software development tasks through intelligent decision-making.",
      problem: "Many engineering tasks involve repetitive browser interactions and manual research. Existing automation solutions follow fixed scripts and lack contextual reasoning — they break the moment a page layout changes or a task requires judgment.",
      whyBuilt: "To bridge AI reasoning with automation by allowing workflows to dynamically adapt based on changing user requirements and application state, making automation resilient rather than brittle.",
      objectives: [
        "Replace fixed-script automation with AI-driven adaptive workflows",
        "Automate research, documentation, and repetitive engineering tasks",
        "Build modular, reusable pipeline components",
        "Integrate seamlessly with the local AI infrastructure",
      ],
      myRole: "Developed all workflow logic, integrated AI models with Playwright browser automation, built reusable automation pipeline modules, and designed the modular workflow execution architecture.",
      architecture: "Workflows are defined as sequences of tasks. Each task can either execute a browser action via Playwright or query a local LLM for a decision. The orchestrator chains these steps, passing context between them. Failed steps trigger retry logic with modified prompts.",
      techStack: [
        { category: "AI", items: ["Ollama", "Local LLMs", "Structured Prompting"] },
        { category: "Automation", items: ["Python", "Playwright", "Workflow Engine"] },
        { category: "Infrastructure", items: ["Docker", "Task Queues"] },
      ],
      challenges: [
        { title: "Prompt Engineering for Reliability", detail: "Getting consistent, structured outputs from LLMs required iterative prompt refinement and output validation layers." },
        { title: "State Management", detail: "Complex workflows need to pass context between steps without losing information or introducing stale data." },
        { title: "Error Recovery", detail: "Automated pipelines must handle failures gracefully — partial retries, fallback strategies, and human escalation checkpoints." },
      ],
      process: [
        "Identified highest-ROI repetitive tasks to automate first",
        "Built basic Playwright automation primitives",
        "Integrated LLM decision layer for adaptive behavior",
        "Developed context-passing mechanism between workflow steps",
        "Added retry and error recovery logic",
        "Packaged common workflows as reusable templates",
      ],
      features: [
        { title: "Adaptive Workflows", detail: "Workflows adjust dynamically based on page state and LLM decisions rather than following rigid scripts." },
        { title: "Modular Pipeline", detail: "Each workflow step is an independent, reusable module that can be combined in different sequences." },
        { title: "Context Propagation", detail: "Information gathered in early steps is available throughout the entire workflow execution." },
        { title: "Error Recovery", detail: "Automatic retry with modified parameters, fallback strategies, and logging for failed steps." },
      ],
      implementation: "The framework uses a directed execution graph where each node is either an AI reasoning step or a browser action. Python dataclasses define workflow schemas. Playwright's async API handles concurrent browser sessions where needed.",
      futureImprovements: [
        "Visual workflow builder UI",
        "Scheduled workflow execution with cron-style triggers",
        "Integration with external APIs and webhooks",
        "Multi-agent workflows with specialized sub-agents",
      ],
      lessonsLearned: [
        "AI-driven automation is only as good as the prompting strategy — vague instructions produce unpredictable results",
        "Modularity pays off quickly — reusable components compound over time",
        "Error handling is the majority of the real engineering work in automation systems",
      ],
    },
  },
  {
    id: "smart-home",
    title: "Smart Home IoT",
    summary: "ESP32-based smart automation system for room automation with modular architecture, wireless control, sensor monitoring, and intelligent device management.",
    stack: "ESP32, C++, IoT, Embedded Systems",
    role: "Solo — Hardware & Software Engineer",
    year: "2026",
    impact: "Built a scalable home automation ecosystem from hardware up.",
    href: "/projects/smart-home",
    tags: ["Solo", "ESP32", "IoT", "Embedded", "Hardware"],
    caseStudy: {
      status: "Active · Ongoing Development",
      overview: "An ESP32-powered home automation platform designed initially for room-level automation and later expanded toward a scalable smart home ecosystem capable of managing connected devices through wireless communication.",
      problem: "Most consumer home automation systems are expensive, proprietary, and difficult to customize. They require vendor lock-in, subscription fees, and provide limited control over automation logic.",
      whyBuilt: "To better understand embedded systems while creating an affordable, fully owned, and modular automation platform that could eventually control an entire home environment without cloud dependency.",
      objectives: [
        "Build a fully self-hosted home automation system",
        "Enable wireless control of room devices",
        "Integrate environmental sensing (temperature, motion, humidity)",
        "Design modular architecture for easy expansion",
        "Keep all data local — no cloud dependency",
      ],
      myRole: "Designed the IoT architecture, programmed ESP32 microcontrollers, integrated wireless communication protocols, developed automation logic, and built a modular foundation for future expansion across multiple rooms.",
      architecture: "ESP32 microcontrollers serve as the primary compute units. Each module connects wirelessly to a central hub. Relay modules handle high-voltage device switching. Sensors feed environmental data into the automation logic. OTA updates allow firmware changes without physical access.",
      techStack: [
        { category: "Hardware", items: ["ESP32", "Relay Modules", "DHT11 Temperature/Humidity", "PIR Motion Sensors"] },
        { category: "Firmware", items: ["C++", "Arduino Framework", "WiFi", "MQTT"] },
        { category: "Automation", items: ["Embedded Logic", "Wireless Communication", "OTA Updates"] },
      ],
      challenges: [
        { title: "Reliable Wireless Communication", detail: "Ensuring stable WiFi connectivity across rooms without interference required careful channel selection and reconnection logic." },
        { title: "Power Management", detail: "Sensor nodes running on battery needed aggressive sleep cycles to extend battery life without missing events." },
        { title: "Safety for High-Voltage Switching", detail: "Relay-based device control required careful hardware isolation and failsafe firmware to prevent unintended switching." },
      ],
      process: [
        "Researched ESP32 capabilities and selected suitable sensor modules",
        "Built and tested single-room prototype",
        "Developed wireless communication layer using MQTT",
        "Integrated environmental sensors (DHT11, PIR)",
        "Built relay control for device switching",
        "Designed modular firmware architecture for multi-room expansion",
        "Implemented OTA update capability",
      ],
      features: [
        { title: "Wireless Device Control", detail: "ESP32 nodes communicate over WiFi/MQTT for reliable, low-latency control of connected devices." },
        { title: "Environmental Monitoring", detail: "DHT11 sensors track temperature and humidity; PIR sensors detect motion for presence-based automation." },
        { title: "Relay Switching", detail: "Relay modules handle switching of standard AC devices safely and reliably." },
        { title: "Modular Architecture", detail: "Each room module is independently deployable and manageable, designed to scale to a full home ecosystem." },
      ],
      implementation: "Each ESP32 node runs custom firmware built on the Arduino framework. MQTT handles bidirectional messaging between nodes and the central hub. The automation logic evaluates sensor readings and schedules to trigger relay outputs. OTA update server allows firmware deployment without physical access.",
      futureImprovements: [
        "Expand to full-home coverage across all rooms",
        "Add voice control integration",
        "Build a local web dashboard for monitoring and control",
        "Integrate energy monitoring for each circuit",
        "Explore Thread/Matter protocol for broader device compatibility",
      ],
      lessonsLearned: [
        "Embedded systems require a completely different mindset — memory and compute are genuinely limited resources",
        "Reliability engineering matters more in hardware than software — flaky connections have physical consequences",
        "Modular design from day one makes the difference between a prototype and an expandable platform",
      ],
    },
  },
  {
    id: "facial-keygen",
    title: "Facial KeyGen",
    summary: "Python-based biometric authentication system that generates cryptographic keys from facial biometrics using computer vision and ML for post-quantum security research.",
    stack: "Python, OpenCV, Machine Learning, Cryptography",
    role: "Solo — Security & ML Engineer",
    year: "2025",
    impact: "Explored biometric-derived key generation as a novel authentication approach.",
    href: "/projects/facial-keygen",
    tags: ["Solo", "Python", "OpenCV", "ML", "Security"],
    caseStudy: {
      status: "Research Complete",
      overview: "A Python-based biometric authentication system that explores generating cryptographic keys from facial biometrics using computer vision and machine learning, motivated by future authentication challenges in a post-quantum computing landscape.",
      problem: "Traditional password-based authentication relies on stored credentials that remain vulnerable to theft, leaks, brute force, and future advances in computing. Post-quantum threats make long-term security of stored secrets increasingly uncertain.",
      whyBuilt: "To explore whether facial biometrics could contribute to cryptographic key generation as an alternative authentication approach — producing keys that are derived rather than stored, making them theoretically impossible to steal from a database.",
      objectives: [
        "Extract stable, repeatable biometric feature vectors from facial images",
        "Derive cryptographic keys deterministically from those features",
        "Explore fuzzy commitment schemes for handling biometric variability",
        "Research applicability as a complementary post-quantum authentication layer",
      ],
      myRole: "Developed the entire computer vision pipeline, implemented biometric feature extraction using MobileNetV2 and Vision Transformer models, designed the key derivation workflow, and conducted security analysis of the approach.",
      architecture: "Face detection via OpenCV locates and normalizes the face region. MobileNetV2 and Vision Transformer extract high-dimensional feature embeddings. A fuzzy commitment scheme maps variable biometric features to a stable key space. PBKDF2 hardens the derived key for cryptographic use.",
      techStack: [
        { category: "Computer Vision", items: ["Python", "OpenCV", "MediaPipe"] },
        { category: "Machine Learning", items: ["MobileNetV2", "Vision Transformer", "Feature Extraction"] },
        { category: "Cryptography", items: ["Fuzzy Commitment", "PBKDF2", "Key Derivation"] },
      ],
      challenges: [
        { title: "Biometric Variability", detail: "Facial features vary with lighting, angle, and expression. The key derivation must produce the same output despite this natural variance — solved with fuzzy commitment schemes." },
        { title: "Feature Stability", detail: "Getting consistent feature embeddings across captures required careful normalization, alignment, and model selection." },
        { title: "Security vs Usability", detail: "Increasing fuzzy tolerance for usability reduces cryptographic security. Finding the right threshold required extensive testing." },
      ],
      process: [
        "Researched biometric key derivation literature and fuzzy commitment schemes",
        "Built face detection and normalization pipeline with OpenCV",
        "Evaluated multiple ML models for feature embedding quality",
        "Selected MobileNetV2 + Vision Transformer for embedding extraction",
        "Implemented fuzzy commitment scheme for variable-to-stable key mapping",
        "Applied PBKDF2 key hardening on derived values",
        "Tested recognition accuracy and key consistency across varied conditions",
      ],
      features: [
        { title: "Face Detection & Normalization", detail: "OpenCV detects and aligns face regions to a canonical orientation before feature extraction." },
        { title: "Deep Feature Extraction", detail: "MobileNetV2 and Vision Transformer produce rich, high-dimensional embeddings capturing unique facial geometry." },
        { title: "Fuzzy Key Derivation", detail: "Fuzzy commitment scheme bridges the gap between variable biometrics and deterministic cryptographic keys." },
        { title: "Key Hardening", detail: "PBKDF2 applies cryptographic hardening to the derived key before use." },
      ],
      implementation: "The pipeline processes captured face images through alignment, embedding extraction, and commitment scheme stages. The fuzzy commitment maps the high-dimensional embedding to a fixed error-correcting code space, producing a stable binary string from which PBKDF2 derives the final key. Enrollment stores only the commitment, not the raw biometric.",
      futureImprovements: [
        "Explore liveness detection to prevent spoofing attacks",
        "Test with larger biometric datasets for robustness validation",
        "Research integration with hardware security modules",
        "Evaluate as a second factor alongside traditional authentication",
      ],
      lessonsLearned: [
        "Biometric systems must be designed for revocability — if a key is compromised, you need a way to re-enroll",
        "The gap between research-quality accuracy and production-quality reliability is enormous",
        "Fuzzy cryptography is a fascinating field with real practical applications beyond biometrics",
      ],
    },
  },
  {
    id: "airgesture",
    title: "AirGesture",
    summary: "Real-time computer vision app using OpenCV and MediaPipe that translates hand gestures into presentation controls for touchless classroom interaction.",
    stack: "Python, OpenCV, MediaPipe",
    role: "Solo — CV Engineer",
    year: "2025",
    impact: "Enabled fully touchless presentation control using just a webcam.",
    href: "/projects/airgesture",
    tags: ["Solo", "Python", "OpenCV", "MediaPipe", "CV"],
    caseStudy: {
      status: "Complete",
      overview: "A real-time gesture recognition system built using MediaPipe and OpenCV that enables users to control presentations through hand gestures, reducing dependence on traditional input devices.",
      problem: "Teachers and presenters frequently need to interact with keyboards or clickers while presenting, interrupting the natural flow of communication and forcing them to stay close to their device.",
      whyBuilt: "To provide an intuitive touchless interaction system that enables smoother classroom teaching and presentations, letting the presenter move freely while maintaining full control.",
      objectives: [
        "Recognize hand gestures reliably in real-time from a standard webcam",
        "Map gestures to presentation control actions",
        "Maintain low latency to keep interaction feeling natural",
        "Work without specialized hardware — just a webcam",
      ],
      myRole: "Built the gesture recognition pipeline, implemented real-time computer vision processing, designed the gesture-to-command mapping system, and optimized the pipeline for minimal latency.",
      architecture: "MediaPipe Hands detects 21 hand landmarks per frame in real time. A landmark analysis layer classifies gesture patterns. The control dispatcher maps recognized gestures to system keyboard events, enabling control of any presentation software.",
      techStack: [
        { category: "Computer Vision", items: ["Python", "OpenCV", "MediaPipe Hands"] },
        { category: "System Control", items: ["PyAutoGUI", "Keyboard Events"] },
      ],
      challenges: [
        { title: "False Positive Gestures", detail: "Natural hand movement during speech triggered unintended slide changes. Solved by requiring gesture hold duration before triggering actions." },
        { title: "Lighting Sensitivity", detail: "MediaPipe landmark detection degrades in poor lighting. Added preprocessing to normalize webcam input." },
        { title: "Latency", detail: "Processing every frame for landmark detection created perceptible lag. Optimized by skipping frames and caching landmark results." },
      ],
      process: [
        "Researched MediaPipe Hands landmark structure and gesture classification approaches",
        "Built basic landmark visualization and gesture logging",
        "Defined gesture vocabulary: swipe right (next), swipe left (previous), open palm (pause), pinch (pointer toggle)",
        "Implemented gesture classification from landmark positions",
        "Added gesture hold duration to reduce false positives",
        "Integrated PyAutoGUI for system keyboard event dispatch",
        "Tested across different lighting conditions and webcam qualities",
      ],
      features: [
        { title: "Next Slide", detail: "Swipe right with an open hand — moves to the next slide in any presentation." },
        { title: "Previous Slide", detail: "Swipe left with an open hand — moves to the previous slide." },
        { title: "Pause / Blank Screen", detail: "Open palm held still — triggers presentation pause or blank screen." },
        { title: "Laser Pointer", detail: "Index finger point — activates pointer mode, tracking finger position on screen." },
      ],
      implementation: "Each video frame is processed by MediaPipe to extract 21 3D hand landmarks. A rule-based classifier analyzes relative landmark positions and velocity vectors to determine gesture type. Confirmed gestures trigger PyAutoGUI keyboard events that work with PowerPoint, Keynote, Google Slides, and any other presentation software.",
      futureImprovements: [
        "Add ML-based gesture classifier to handle more complex gestures",
        "Support two-hand gestures for zoom and annotation",
        "Build a calibration mode for different hand sizes and webcam positions",
        "Package as a standalone executable for easy installation",
      ],
      lessonsLearned: [
        "Real-time computer vision is as much about filtering bad data as detecting good data",
        "User experience in gesture interfaces requires careful threshold tuning — too sensitive is worse than not sensitive enough",
        "MediaPipe is remarkably powerful for the zero-configuration it requires",
      ],
    },
  },
  {
    id: "etherworld-ios",
    title: "EtherWorld iOS",
    summary: "Designed the application architecture and modular structure for the EtherWorld iOS app — scalable navigation, API integration, and maintainable app structure.",
    stack: "iOS, Swift, Architecture Design, API Integration",
    role: "Solo — Mobile Architect",
    year: "2025",
    impact: "Delivered a production-ready architecture for the EtherWorld mobile platform.",
    href: "/projects/etherworld-ios",
    tags: ["Solo", "iOS", "Swift", "Architecture", "Mobile"],
    caseStudy: {
      status: "Shipped · App Store",
      overview: "A native iOS application developed for the EtherWorld platform that extends the website experience to mobile devices through seamless backend API integration and native application workflows.",
      problem: "EtherWorld users primarily accessed content through web browsers, limiting the overall mobile experience and discoverability within Apple's ecosystem. A native app was needed to reach a broader mobile audience.",
      whyBuilt: "To deliver a native iOS experience while maintaining consistency with the existing platform and successfully publishing through Apple's deployment process.",
      objectives: [
        "Build a native iOS app consistent with the EtherWorld brand",
        "Integrate backend REST APIs for content delivery",
        "Architect for scalability and future feature additions",
        "Successfully deploy through App Store Connect",
      ],
      myRole: "Developed the full iOS application, integrated backend REST APIs, built native user interfaces in Swift, managed App Store Connect deployment, and prepared TestFlight builds for review.",
      architecture: "SwiftUI handles declarative UI construction. A dedicated networking layer abstracts all API communication. Navigation uses a coordinator pattern for clean separation between routing and view logic. The data layer uses Combine for reactive state management.",
      techStack: [
        { category: "Mobile", items: ["Swift", "SwiftUI", "iOS"] },
        { category: "Networking", items: ["REST APIs", "JSON", "URLSession", "Combine"] },
        { category: "Deployment", items: ["Xcode", "App Store Connect", "TestFlight"] },
      ],
      challenges: [
        { title: "API Consistency", detail: "Ensuring the mobile app presented the same data as the web platform required careful API contract definition and response normalization." },
        { title: "App Store Review", detail: "Navigating Apple's review process required attention to metadata, content policies, and privacy disclosure requirements." },
        { title: "Navigation Architecture", detail: "Designing a navigation system that could scale to future features without refactoring required upfront architectural decisions." },
      ],
      process: [
        "Defined app information architecture and navigation flows",
        "Set up Xcode project with modular target structure",
        "Built networking layer with URLSession and Combine",
        "Developed core content views in SwiftUI",
        "Integrated backend APIs and tested data flows",
        "Prepared App Store metadata, screenshots, and privacy policy",
        "Submitted TestFlight builds and iterated on feedback",
        "Released through App Store Connect",
      ],
      features: [
        { title: "Native Content Browser", detail: "Native SwiftUI views for browsing EtherWorld articles and research content." },
        { title: "API Integration", detail: "Full backend integration delivering the same content as the web platform to mobile users." },
        { title: "Offline Reading", detail: "Cached content available for offline reading of previously loaded articles." },
        { title: "App Store Presence", detail: "Available on the Apple App Store with full iOS native experience." },
      ],
      implementation: "The app uses a coordinator pattern for navigation, separating routing logic from view controllers. API responses are decoded into typed Swift models using Codable. Combine publishers handle async state updates throughout the UI layer. The modular architecture allows independent development of new features.",
      futureImprovements: [
        "Push notifications for new content and protocol updates",
        "Offline-first architecture with local caching database",
        "Widgets for home screen Ethereum news",
        "iPad-optimized layout",
      ],
      lessonsLearned: [
        "Apple's review process requires careful preparation — metadata and privacy policy are as important as the code",
        "SwiftUI's declarative model makes complex UI significantly faster to build than UIKit",
        "Architecture decisions made on day one are much harder to change once features accumulate",
      ],
    },
  },
  {
    id: "eipsinsight",
    title: "EIPsInsight",
    summary: "Ethereum governance analytics platform for tracking EIP lifecycles and governance signals.",
    stack: "React, TypeScript, Data viz, Web3 analytics",
    role: "Team — Frontend Contributor",
    year: "2024",
    impact: "Contributed frontend work to a project that received Ethereum Foundation ESP grant support.",
    href: "/projects/eipsinsight",
    tags: ["Team", "Governance", "React", "Analytics"],
    caseStudy: {
      status: "Live · Ethereum Foundation Supported",
      github: "https://github.com/ethereum/EIPs",
      overview: "A governance analytics platform that visualizes Ethereum Improvement Proposal (EIP) activity, contributor insights, proposal lifecycles, and ecosystem metrics through interactive dashboards and structured reporting.",
      problem: "Ethereum governance information is distributed across multiple repositories, GitHub discussions, and community forums, making proposal tracking and contributor analysis difficult for researchers and community members.",
      whyBuilt: "To improve visibility into Ethereum governance by providing contributors, researchers, and community members with centralized analytics and actionable insights into the EIP process.",
      objectives: [
        "Centralize EIP lifecycle data into a single analytics platform",
        "Visualize proposal progression and historical trends",
        "Surface contributor activity and governance participation",
        "Support Ethereum governance researchers with structured data",
      ],
      myRole: "Contributed as a frontend developer on the team. Developed production features, built analytics dashboards, designed backend reporting workflows, improved data visualization components, and integrated contributor analytics.",
      architecture: "Next.js powers the frontend with React components for dashboard views. Data is fetched from GitHub APIs and processed into analytics-ready formats. Chart libraries render governance metrics. The platform received Ethereum Foundation ESP grant support.",
      techStack: [
        { category: "Frontend", items: ["React", "Next.js", "TypeScript"] },
        { category: "Data Visualization", items: ["Charts", "Data Viz Libraries", "Analytics"] },
        { category: "APIs", items: ["GitHub API", "Web3 Data", "Backend APIs"] },
      ],
      challenges: [
        { title: "Data Normalization", detail: "EIP data comes from multiple sources in inconsistent formats. Normalizing this into a unified schema required careful data pipeline work." },
        { title: "Performance at Scale", detail: "Rendering analytics for thousands of proposals and contributors required virtualization and intelligent data pagination." },
        { title: "Real-time Updates", detail: "Governance activity changes frequently. Keeping dashboard data fresh without overwhelming API rate limits required smart caching strategies." },
      ],
      process: [
        "Joined the team and onboarded to the existing codebase",
        "Identified priority features for governance visibility",
        "Built dashboard components for EIP lifecycle visualization",
        "Integrated contributor analytics features",
        "Improved data visualization for proposal trends",
        "Collaborated with team on Ethereum Foundation ESP grant milestones",
      ],
      features: [
        { title: "EIP Lifecycle Tracking", detail: "Visualizes every stage of the EIP process from draft through final or withdrawn status." },
        { title: "Contributor Analytics", detail: "Surfaces activity patterns and contributions of EIP authors and reviewers." },
        { title: "Governance Trends", detail: "Historical trend data showing governance activity over time." },
        { title: "Proposal Search & Filter", detail: "Advanced filtering by category, status, author, and time period." },
      ],
      implementation: "Frontend built with React and TypeScript. Dashboard components use chart libraries for governance visualizations. Data pipeline normalizes GitHub API responses into analytics-ready formats. The platform is deployed and maintained with Ethereum Foundation ESP grant support.",
      futureImprovements: [
        "Real-time notification system for EIP status changes",
        "Integration with Ethereum governance forums and discussion threads",
        "Machine learning models for proposal outcome prediction",
        "API access for researchers and third-party integrations",
      ],
      lessonsLearned: [
        "Contributing to an existing codebase requires reading more code than you write — understanding before changing",
        "Governance data is messy — the infrastructure to clean and normalize it is as important as the visualization",
        "Open source collaboration has a different dynamic than solo projects — communication is as important as code quality",
      ],
    },
  },
  {
    id: "portfolio",
    title: "This Portfolio",
    summary: "Immersive developer portfolio with a 3D dome gallery, scroll-driven animations, and an editorial bronze design system.",
    stack: "Next.js, TypeScript, Three.js, Framer Motion, CSS",
    role: "Solo — Design & Engineering",
    year: "2026",
    impact: "Built entirely from scratch — 3D canvas, animation system, content architecture, and design.",
    href: "/projects/portfolio",
    tags: ["Solo", "Next.js", "3D", "Design"],
    caseStudy: {
      status: "Live · This Site",
      live: "https://ayushetty.com",
      overview: "A personal engineering portfolio designed to showcase production software, engineering case studies, technical writing, and professional experience through a modern, interactive, and performance-focused user experience.",
      problem: "Traditional portfolios provide only brief project summaries, making it difficult for recruiters and collaborators to understand the engineering process, technical depth, and problem-solving approach behind each project.",
      whyBuilt: "To create a portfolio that emphasizes engineering thinking through detailed project case studies, clean design, and technical storytelling — presenting work the way engineering companies like Stripe and Vercel present their own products.",
      objectives: [
        "Showcase engineering depth through full case studies",
        "Create an immersive, memorable first impression",
        "Build a design system that scales across all content types",
        "Achieve excellent performance despite rich interactivity",
        "Make the portfolio itself a project worth showcasing",
      ],
      myRole: "Designed the entire UI/UX, developed all frontend code, implemented the 3D dome gallery, built the animation system, created reusable component library, and architected the content system.",
      architecture: "Next.js App Router with React Server Components for optimal performance. Three.js powers the 3D dome gallery on the homepage. Framer Motion handles complex animations. Lenis provides smooth scroll behavior. CSS custom properties implement the design token system across light and dark modes.",
      techStack: [
        { category: "Framework", items: ["Next.js 16", "React", "TypeScript"] },
        { category: "3D & Animation", items: ["Three.js", "Framer Motion", "CSS Animations", "Lenis"] },
        { category: "Design System", items: ["CSS Custom Properties", "Mona Sans", "Hubot Sans", "TailwindCSS"] },
        { category: "Deployment", items: ["Vercel", "Edge Network"] },
      ],
      challenges: [
        { title: "3D Performance", detail: "Rendering a sphere of images in Three.js while maintaining smooth 60fps scroll required careful geometry optimization and texture management." },
        { title: "Light/Dark Mode Consistency", detail: "Maintaining a coherent bronze editorial aesthetic across both modes required a carefully designed token system rather than simple color inversions." },
        { title: "Scroll System Conflicts", detail: "Lenis smooth scroll conflicted with LinkedIn iframe embeds, the 3D gallery touch handling, and various overflow behaviors — required systematic debugging." },
      ],
      process: [
        "Defined design language — monochrome + bronze editorial aesthetic",
        "Built 3D dome gallery as the hero interactive element",
        "Developed navigation and routing architecture",
        "Created the journey timeline section with photo galleries",
        "Built all subpages with consistent design system",
        "Designed and implemented project case study template",
        "Added marquee ticker, pixel scramble text, and tilt card stack",
        "Tuned performance, scroll behavior, and accessibility",
      ],
      features: [
        { title: "3D Dome Gallery", detail: "Interactive sphere of photos rendered in Three.js — drag to rotate, click to enlarge." },
        { title: "Hover-Dial Projects", detail: "Slide cursor left/right to scrub through projects with velocity-based fan spread." },
        { title: "Pixel Scramble Text", detail: "Character-by-character scramble animation on hero headings using intersection observer." },
        { title: "Journey Timeline", detail: "Full visual timeline of events with photo galleries and story modals." },
        { title: "Spotlight Project List", detail: "Hover-activated spotlight rows for the projects page — non-hovered rows dim out." },
      ],
      implementation: "The site uses Next.js App Router with a clear separation between Server and Client Components. The 3D gallery is isolated in a client component with a server-rendered fallback. CSS custom properties handle the complete design token system. All animations respect prefers-reduced-motion.",
      futureImprovements: [
        "Add WebGL shader effects to the dome gallery",
        "Build a blog section for technical writing",
        "Add cursor follower effects",
        "Animate page transitions with View Transitions API",
      ],
      lessonsLearned: [
        "Building your portfolio is one of the best ways to push your own technical boundaries",
        "Design systems pay off immediately — consistent tokens make every new component faster",
        "The intersection of design and engineering is where the most interesting work happens",
      ],
    },
  },
];
